[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 180
initialDelaySeconds = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
